name: "Prettier Commit Checks"
description: Run Prettier checks

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Run Prettier
      shell: bash
      run: npx prettier --check .
