name: "Run End to End Tests"
description: Run End to End Tests

inputs:
  PROXYGEN_URL_PATH:
    description: "The URL path for the Proxygen API, e.g. 'im1-pfs-auth-pr-31'"
    required: true
  ENVIRONMENT:
    description: "The environment to deploy to, e.g. 'internal-dev', 'internal-qa', 'internal-prod'"
    required: true
  PROXY_NAME:
    description: "The name of the proxy to test, e.g. 'im1-pfs-auth--internal-dev--im1-pfs-auth-pr-31'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo
      shell: bash
      run: echo "Running End to End Tests"
