name: "Ruff Format"
description: Run Ruff format

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync --all-extras
      shell: bash
    - name: Run Ruff Format
      shell: bash
      run: uv run ruff format .
