version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/" # Covers .github/workflows
      - ".github/actions/check-english-usage"
      - ".github/actions/check-file-format"
      - ".github/actions/check-github-actions"
      - ".github/actions/check-markdown-format"
      - ".github/actions/create-lines-of-code-report"
      - ".github/actions/perform-static-analysis"
      - ".github/actions/prettier-commit-checks"
      - ".github/actions/scan-dependencies"
      - ".github/actions/scan-secrets"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directories:
      - "/"
    schedule:
      interval: "monthly"
    groups:
      uv-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/sandbox"
    schedule:
      interval: "monthly"
    groups:
      docker-images:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
