[project]
name = "im1-pfs-auth"
version = "0.1.0"
description = "IM1 PFS Auth API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff"
]
