[project]
name = "im1-pfs-auth"
version = "0.1.0"
description = "IM1 PFS Auth API"
readme = "README.md"
requires-python = "~=3.13.0"

[dependency-groups]
app = [
  "flask~=3.1.1",
  "pydantic==2.9.2",
  "gunicorn~=23.0.0",
  "requests~=2.32.5",
  "pyjwt~=2.8.0",
  "cryptography~=42.0.0",
]
sandbox = ["flask~=3.1.1", "gunicorn~=23.0.0"]
dev = [
  "coverage==7.10.4",
  "pytest-cov==6.2.1",
  "pytest-nhsd-apim==5.0.3",
  "pytest==8.2.0",
  "requests==2.32.0",
  "ruff==0.12.9",
]

[tool.uv]
required-version = "~=0.8.0"
package = false
default-groups = "all"
override-dependencies = ["typing-extensions==4.12.2", "requests==2.32.5"]

[tool.coverage.run]
branch = true
omit = ["app/api/tests/*", "sandbox/tests/*"]

[tool.ruff]
target-version = "py313"
extend-exclude = ["docs/adr"]

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
  "COM812",  # Ignore due to conflict with Ruff formatter
  "ISC001",  # Ignore due to conflict with Ruff formatter
  "PLR2004", # Ignore magic value
  "D104",    # Ignore missing docstring in public package
  "D100",    # Ignore missing docstring in public module
  "N999",    # Ignore invalid module name
]

[tool.ruff.lint.per-file-ignores]
"app/*.py" = ["TID252"]
"app/api/domain/forward_request_model.py" = ["N805"] # Pydantic basemodel needs cls instead of self
"**test_*.py" = ["S101", "D102", "D103", "SLF001", "PT019", "PLR0913"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-local-folder = ["tests", "api", "app", "sandbox"]
