name: "Prettier Commit Checks"
description: Run Prettier checks

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 22
    - name: Install dependencies
      shell: bash
      run: npm install -g prettier
    - name: Run Prettier
      shell: bash
      run: npx prettier --check .
