name: "Check uv lock"
description: Check uv lock

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
    - name: Install dependencies
      run: uv sync --all-groups
      shell: bash
    - name: Run uv lock check
      shell: bash
      run: uv lock --check
