name: Run Unit Tests
description: Installs pytest and runs tests
runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync --all-extras
      shell: bash
    - name: Run Unit Tests
      run: make sandbox-test
      shell: bash
