name: Run Tests
description: Installs pytest and runs tests
runs:
  using: "composite"
  steps:
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: pip install uv
      shell: bash
    - run: make install
      shell: bash
    - run: make test
      shell: bash
