runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Generate Postman Collection
      shell: bash
      run: make postman-generate-collection

    - name: Upload Postman Collection
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.POSTMAN_COLLECTION_FILE_NAME }}
        path: ${{ env.POSTMAN_COLLECTION_PATH }}
