name: "Ruff Checks"
description: Run Ruff checks

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync --all-extras
      shell: bash
    - name: Run Ruff Check
      shell: bash
      run: uv run ruff check .
