name: "Ruff Checks"
description: Run Ruff checks

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
    - name: Install dependencies
      run: uv sync --all-groups
      shell: bash
    - name: Run Ruff Check
      shell: bash
      run: uv run ruff check .
