name: "Build Container"
description: Build Container

inputs:
  type_of_deployment:
    description: "Type of deployment (app or sandbox)"
    required: true
  use_mock:
    description: "Whether or not the mock for routing requests is on or off"
    type: string
    required: false

runs:
  using: "composite"
  steps:
    - name: Build Container
      shell: bash
      run: make ${{ inputs.type_of_deployment }}-build
      env:
        PROXYGEN_DOCKER_REGISTRY_URL: example.com/${{ inputs.type_of_deployment }}
        CONTAINER_TAG: ${{ github.sha }}
        USE_MOCK: ${{ inputs.use_mock }}
