name: "Core Code Checks"
# Core code checks for the repository, used to block deployment if any checks fail.

# Reusable workflow for code checks, used in both pull requests (workflow called) and main branch pushes.

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  actionlint-check:
    name: "Check GitHub Actions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

  scan-secrets:
    name: "Scan Secrets"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Scan Secrets"
        uses: ./.github/actions/scan-secrets

  check-file-format:
    name: "Check File Format (editorconfig)"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check File Format"
        uses: ./.github/actions/check-file-format

  check-uv-lock:
    name: "Check pyproject.toml is Locked"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check uv Lock"
        uses: ./.github/actions/check-uv-lock

  scan-dependencies:
    name: "Scan Dependencies"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Scan Dependencies"
        uses: ./.github/actions/scan-dependencies

  build-sandbox-container:
    name: "Build Sandbox Container"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Build Container"
        uses: ./.github/actions/build-container
        with:
          type_of_deployment: "sandbox"

  build-app-container:
    name: "Build App Container"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Build Container"
        uses: ./.github/actions/build-container
        with:
          type_of_deployment: "app"

  generate-postman-collection:
    name: "Generate Postman Collection"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Generate Postman Collection"
        uses: ./.github/workflows/reuseable-generate-postman-collection.yml
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          environment: "internal-dev-sandbox"
          additional_path: "pr-${{ github.event.number }}"
