name: "Code Checks"

# Reusable workflow for code checks, used in both pull requests (workflow called) and main branch pushes.

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  prettier-checks:
    name: "Prettier Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Prettier Checks"
        uses: ./.github/actions/prettier-commit-checks

  ruff-checks:
    name: "Ruff Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Ruff Checks"
        uses: ./.github/actions/ruff-checks

  ruff-format:
    name: "Ruff Format"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Ruff Format"
        uses: ./.github/actions/ruff-format

  actionlint-check:
    name: "Check GitHub Actions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

  scan-secrets:
    name: "Scan Secrets"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Scan Secrets"
        uses: ./.github/actions/scan-secrets

  check-file-format:
    name: "Check File Format (editorconfig)"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check File Format"
        uses: ./.github/actions/check-file-format

  check-markdown-format:
    name: "Check Markdown Format"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check Markdown Format"
        uses: ./.github/actions/check-markdown-format

  check-english-usage:
    name: "Check English Usage (vale)"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check English Usage"
        uses: ./.github/actions/check-english-usage

  check-uv-lock:
    name: "Check pyproject.toml is Locked"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Check uv Lock"
        uses: ./.github/actions/check-uv-lock

  run-unit-tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Run unit tests"
        uses: ./.github/actions/run-unit-tests

  scan-dependencies:
    name: "Scan Dependencies"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Scan Dependencies"
        uses: ./.github/actions/scan-dependencies

  build-sandbox:
    name: "Build Sandbox"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Build Sandbox"
        uses: ./.github/actions/build-sandbox

